version: '3.4'

services:
  api:
    container_name: sistema-aleitamento-api
    restart: always
    build: ./SistemaAleitamentoMaternoApi/SistemaAleitamentoMaternoApi
    ports:
      - 5000:5000
    depends_on:
      - db
  web:
    container_name: sistema-aleitamento-ui
    restart: always
    build: ./SistemaAleitamentoUI
    ports:
      - 8080:80
    depends_on:
      - api
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=sistema_aleitamento_materno
    ports:
      - '5440:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
