version: '3.4'

services:
  api:
    container_name: sistema-aleitamento-api
    restart: always
    build: ./SistemaAleitamentoMaternoApi/SistemaAleitamentoMaternoApi
    ports:
      - 5000:5000
    depends_on:
      - postgres
  web:
    container_name: sistema-aleitamento-ui
    restart: always
    build: ./SistemaAleitamentoUI
    ports:
      - 8080:80
    depends_on:
      - api
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=sistema_aleitamento_materno
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  db:
    driver: local
